"""Store protocols for source-of-truth backend modules."""

from __future__ import annotations

from typing import Protocol

from control_plane_kit.stores.records import (
    ActivityEventRecord,
    ActivityPlanRecord,
    ActivityRunRecord,
    ApprovalDecisionRecord,
    ApprovalRequestRecord,
    GraphVersionRecord,
    InstanceRecord,
    ObservationRecord,
    OperationActionRecord,
    OperationSessionRecord,
    SecretReferenceRecord,
    WorkspaceLifecycle,
    WorkspaceRecord,
)


class WorkspaceStore(Protocol):
    """Owns workspace identity and graph pointers."""

    def create(self, record: WorkspaceRecord) -> WorkspaceRecord: ...
    def get(self, workspace_id: str) -> WorkspaceRecord: ...
    def get_for_update(self, workspace_id: str) -> WorkspaceRecord: ...
    def set_lifecycle(self, workspace_id: str, lifecycle: WorkspaceLifecycle) -> WorkspaceRecord: ...
    def set_current_graph(self, workspace_id: str, graph_id: str) -> WorkspaceRecord: ...
    def set_desired_graph(self, workspace_id: str, graph_id: str) -> WorkspaceRecord: ...


class GraphTopologyStore(Protocol):
    """Owns graph-shaped topology versions behind an adapter."""

    def save(self, record: GraphVersionRecord) -> GraphVersionRecord: ...
    def get(self, graph_id: str) -> GraphVersionRecord: ...
    def latest_for_workspace(self, workspace_id: str) -> GraphVersionRecord | None: ...
    def next_version_for_workspace(self, workspace_id: str) -> int: ...


class ActivityHistoryStore(Protocol):
    """Owns structured operational memory."""

    def add_session(self, record: OperationSessionRecord) -> OperationSessionRecord: ...
    def lock_session_idempotency(self, workspace_id: str, idempotency_key: str) -> None: ...
    def get_session(self, session_id: str) -> OperationSessionRecord: ...
    def session_for_idempotency(
        self, workspace_id: str, idempotency_key: str
    ) -> OperationSessionRecord | None: ...
    def sessions_for_workspace(self, workspace_id: str) -> tuple[OperationSessionRecord, ...]: ...
    def update_session(self, record: OperationSessionRecord) -> OperationSessionRecord: ...
    def add_action(self, record: OperationActionRecord) -> OperationActionRecord: ...
    def action_for_idempotency(
        self, session_id: str, idempotency_key: str
    ) -> OperationActionRecord | None: ...
    def next_action_ordinal(self, session_id: str) -> int: ...
    def actions_for_session(self, session_id: str) -> tuple[OperationActionRecord, ...]: ...
    def add_approval_request(
        self, record: ApprovalRequestRecord
    ) -> ApprovalRequestRecord: ...
    def get_approval_request(self, request_id: str) -> ApprovalRequestRecord: ...
    def approval_request_for_idempotency(
        self, session_id: str, idempotency_key: str
    ) -> ApprovalRequestRecord | None: ...
    def approval_requests_for_session(
        self, session_id: str
    ) -> tuple[ApprovalRequestRecord, ...]: ...
    def add_approval_decision(
        self, record: ApprovalDecisionRecord
    ) -> ApprovalDecisionRecord: ...
    def approval_decision_for_request(
        self, request_id: str
    ) -> ApprovalDecisionRecord | None: ...
    def approval_decision_for_idempotency(
        self, request_id: str, idempotency_key: str
    ) -> ApprovalDecisionRecord | None: ...
    def add_plan(self, record: ActivityPlanRecord) -> ActivityPlanRecord: ...
    def get_plan(self, plan_id: str) -> ActivityPlanRecord: ...
    def plans_for_session(self, session_id: str) -> tuple[ActivityPlanRecord, ...]: ...
    def add_run(self, record: ActivityRunRecord) -> ActivityRunRecord: ...
    def runs_for_plan(self, plan_id: str) -> tuple[ActivityRunRecord, ...]: ...
    def add_event(self, record: ActivityEventRecord) -> ActivityEventRecord: ...
    def events_for_run(self, run_id: str) -> tuple[ActivityEventRecord, ...]: ...


class ObservedStateStore(Protocol):
    """Owns runtime observations without rewriting desired topology."""

    def put(self, record: ObservationRecord) -> ObservationRecord: ...
    def latest(self, workspace_id: str, subject_id: str) -> ObservationRecord | None: ...
    def latest_for_workspace(self, workspace_id: str) -> tuple[ObservationRecord, ...]: ...
    def history(self, workspace_id: str, subject_id: str) -> tuple[ObservationRecord, ...]: ...


class InstanceRegistryStore(Protocol):
    """Owns Hub-visible control-plane instance records."""

    def register(self, record: InstanceRecord) -> InstanceRecord: ...
    def get(self, instance_id: str) -> InstanceRecord: ...
    def set_lifecycle(self, instance_id: str, lifecycle: WorkspaceLifecycle) -> InstanceRecord: ...
    def list_for_owner(self, owner_id: str) -> tuple[InstanceRecord, ...]: ...


class SecretReferenceStore(Protocol):
    """Owns secret references, never secret values."""

    def assign(self, record: SecretReferenceRecord) -> SecretReferenceRecord: ...
    def get(self, secret_ref: str) -> SecretReferenceRecord: ...
    def exists(self, secret_ref: str) -> bool: ...
