"""Public API for control-plane-kit."""

from control_plane_kit.capabilities import (
    CAPABILITIES,
    DRAINABLE,
    HEALTH_CHECKABLE,
    LOG_READABLE,
    METRICS_READABLE,
    OBSERVER_MUTABLE,
    RESTARTABLE,
    SWITCHABLE,
    TARGET_MUTABLE,
    Capability,
    CapabilityName,
    capability_named,
)
from control_plane_kit.algebra import (
    ApplicationBlock,
    BlockSpec,
    DataBlock,
    DeploymentRecipe,
    DockerRuntime,
    ExternalRuntime,
    ProxyBlock,
    RoleInputSocket,
    RoleOutputSocket,
    RoleSockets,
    RuntimeContext,
    SocketConnection,
)
from control_plane_kit.compiler import compile_recipe
from control_plane_kit.control_routes import (
    COMMON_STATUS_ROUTES,
    CONTROL_ROUTE_SETS,
    DEFAULT_CONTROL_PREFIX,
    LOG_ROUTES,
    OBSERVER_ROUTES,
    TARGET_ROUTES,
    ControlRoute,
    ControlRouteMethod,
    ControlRouteScope,
    ControlRouteSet,
    ControlRouteSetName,
    control_path,
    route_set_named,
)
from control_plane_kit.graph import DeploymentGraph, Edge, Endpoint, Node, RuntimeRecord
from control_plane_kit.implementations import (
    DockerImageImplementation,
    DockerPostgresImplementation,
    ExternalHttpImplementation,
    ExternalPostgresImplementation,
    ExternalTcpImplementation,
    LocalSourceImplementation,
    PlanOnlyImplementation,
)
from control_plane_kit.servers import BlockControlState, create_block_control_app
from control_plane_kit.planner import (
    Activity,
    ActivityPlan,
    GraphDiff,
    diff_graphs,
    plan_migration,
)
from control_plane_kit.types import EndpointScope, Protocol, RuntimeKind

__all__ = [
    "Activity",
    "ActivityPlan",
    "ApplicationBlock",
    "BlockSpec",
    "CAPABILITIES",
    "DRAINABLE",
    "HEALTH_CHECKABLE",
    "LOG_READABLE",
    "METRICS_READABLE",
    "OBSERVER_MUTABLE",
    "RESTARTABLE",
    "SWITCHABLE",
    "TARGET_MUTABLE",
    "Capability",
    "BlockControlState",
    "create_block_control_app",
    "CapabilityName",
    "capability_named",
    "COMMON_STATUS_ROUTES",
    "CONTROL_ROUTE_SETS",
    "DEFAULT_CONTROL_PREFIX",
    "LOG_ROUTES",
    "OBSERVER_ROUTES",
    "TARGET_ROUTES",
    "ControlRoute",
    "ControlRouteMethod",
    "ControlRouteScope",
    "ControlRouteSet",
    "ControlRouteSetName",
    "control_path",
    "route_set_named",
    "DataBlock",
    "DeploymentGraph",
    "DeploymentRecipe",
    "DockerImageImplementation",
    "DockerPostgresImplementation",
    "DockerRuntime",
    "Edge",
    "Endpoint",
    "EndpointScope",
    "ExternalHttpImplementation",
    "ExternalPostgresImplementation",
    "ExternalRuntime",
    "ExternalTcpImplementation",
    "GraphDiff",
    "LocalSourceImplementation",
    "Node",
    "PlanOnlyImplementation",
    "Protocol",
    "ProxyBlock",
    "RoleInputSocket",
    "RoleOutputSocket",
    "RoleSockets",
    "RuntimeContext",
    "RuntimeKind",
    "RuntimeRecord",
    "SocketConnection",
    "compile_recipe",
    "diff_graphs",
    "plan_migration",
]
