"""Pure deployment language used before operational execution."""

__version__ = "0.1.0"

from control_plane_kit_core.products import (
    ContainerServerProduct,
    ContainerServerProductCodec,
    ContainerServerProductError,
    DuplicateProductIdentity,
    OciImageReference,
    OciImageReferenceCodec,
    OciImageReferenceError,
    OciPlatform,
    PlatformMismatch,
    ProductCatalog,
    ProductCatalogConflict,
    ProductCatalogError,
    ProductDescriptorCodec,
    ProductDescriptorDocument,
    ProductDescriptorError,
    ProductIdentity,
    ProductIdentityCodec,
    ProductIdentityError,
    ProductInstanceConfiguration,
    ProductInstantiationError,
    OciContainerProductImplementation,
    ProductRuntimeContract,
    ProductRuntimeContractCodec,
    ProductRuntimeContractError,
    UnknownProductIdentity,
    instantiate_catalog_product,
    instantiate_product,
    require_unique_product_identities,
)

__all__ = [
    "ContainerServerProduct",
    "ContainerServerProductCodec",
    "ContainerServerProductError",
    "DuplicateProductIdentity",
    "OciImageReference",
    "OciImageReferenceCodec",
    "OciImageReferenceError",
    "OciPlatform",
    "PlatformMismatch",
    "ProductCatalog",
    "ProductCatalogConflict",
    "ProductCatalogError",
    "ProductDescriptorCodec",
    "ProductDescriptorDocument",
    "ProductDescriptorError",
    "ProductIdentity",
    "ProductIdentityCodec",
    "ProductIdentityError",
    "ProductInstanceConfiguration",
    "ProductInstantiationError",
    "OciContainerProductImplementation",
    "ProductRuntimeContract",
    "ProductRuntimeContractCodec",
    "ProductRuntimeContractError",
    "UnknownProductIdentity",
    "instantiate_catalog_product",
    "instantiate_product",
    "require_unique_product_identities",
]
