"""Optional server adapters for control-plane-kit."""

from control_plane_kit.servers._templates import GeneratedServerSyntaxError
from control_plane_kit.servers.block_control import BlockControlState, create_block_control_app
from control_plane_kit.servers.hello import (
    HelloDependency,
    HelloEnvironment,
    hello_command,
    hello_server_block,
)
from control_plane_kit.servers.http_active_router import (
    HttpActiveRouterRuntime,
    HttpActiveRouterServer,
    http_active_router_block,
    http_active_router_command,
)
from control_plane_kit.servers.http_circuit_breaker import (
    CircuitBreakerMethodPolicy,
    CircuitBreakerObservation,
    CircuitBreakerPolicy,
    CircuitBreakerState,
    HttpCircuitBreakerServer,
    http_circuit_breaker_block,
    http_circuit_breaker_command,
)
from control_plane_kit.servers.http_bulkhead import (
    BulkheadObservation,
    BulkheadOutcome,
    HttpBulkheadPolicy,
    HttpBulkheadServer,
    http_bulkhead_block,
    http_bulkhead_command,
)
from control_plane_kit.servers.http_cache import (
    CacheObservation,
    CacheOutcome,
    CacheVaryHeader,
    HttpCachePolicy,
    HttpCacheServer,
    http_cache_block,
    http_cache_command,
)
from control_plane_kit.servers.http_fault_injector import (
    ConnectionTerminationFault,
    DelayFault,
    DisabledFaultInjection,
    EnabledFaultInjection,
    FaultInjectionLimits,
    FaultInjectionObservation,
    FaultInjectionState,
    FaultKind,
    HttpFault,
    HttpFaultInjectionServer,
    InjectedConnectionTermination,
    InjectedHttpStatus,
    SeededProbabilityFault,
    StatusFault,
    TargetOutcome,
    TruncationFault,
    fault_injection_state_descriptor,
    fault_injection_state_from_descriptor,
    http_fault_injector_block,
    http_fault_injector_command,
)
from control_plane_kit.servers.http_messages import HttpHandler, HttpRequest, HttpResponse
from control_plane_kit.servers.http_multiplexer import (
    HttpMultiplexerRuntime,
    HttpMultiplexerServer,
    http_multiplexer_block,
    http_multiplexer_command,
)
from control_plane_kit.servers.http_proxy import HttpProxyRuntime, HttpProxyServer, http_proxy_block, http_proxy_command
from control_plane_kit.servers.http_rate_limiter import (
    HttpRateLimiterRuntime,
    HttpRateLimiterServer,
    http_rate_limiter_block,
    http_rate_limiter_command,
)
from control_plane_kit.servers.http_retry import (
    HttpRetryServer,
    RetryMethodPolicy,
    RetryObservation,
    RetryPolicy,
    RetryStatusPolicy,
    http_retry_block,
    http_retry_command,
)
from control_plane_kit.servers.http_traffic_logger import (
    HttpTrafficLoggerServer,
    TrafficEvidence,
    TrafficEvidencePage,
    TrafficEvidencePolicy,
    TrafficMethod,
    TrafficPathPolicy,
    TrafficStatusClass,
    http_traffic_logger_block,
    http_traffic_logger_command,
)
from control_plane_kit.servers.http_timeout import (
    HttpTimeoutServer,
    HttpTimeoutPolicy,
    TimeoutObservation,
    TimeoutOutcome,
    http_timeout_block,
    http_timeout_command,
)
from control_plane_kit.servers.http_weighted_balancer import (
    HttpWeightedLoadBalancerRuntime,
    HttpWeightedLoadBalancerServer,
    http_weighted_load_balancer_block,
    http_weighted_load_balancer_command,
)
from control_plane_kit.servers.instance_read import create_instance_read_app
from control_plane_kit.servers.managed_http_router import (
    ManagedRouterEnvironment,
    ManagedRouterSettings,
    create_managed_http_router_app,
    managed_http_router_block,
)
from control_plane_kit.servers.request_observer import (
    RequestObservation,
    RequestObserverServer,
    request_observer_block,
    request_observer_command,
)
from control_plane_kit.servers.catalog import (
    PACKAGE_SERVER_CONTRACTS,
    CapabilityImplementation,
    ExecutableCapability,
    PackageServerContract,
    ProductMaturity,
    UnsupportedCapability,
    package_server_contract,
)

__all__ = [
    "BlockControlState",
    "BulkheadObservation",
    "BulkheadOutcome",
    "CacheObservation",
    "CacheOutcome",
    "CacheVaryHeader",
    "GeneratedServerSyntaxError",
    "HelloDependency",
    "HelloEnvironment",
    "HttpActiveRouterRuntime",
    "HttpActiveRouterServer",
    "CircuitBreakerMethodPolicy",
    "CircuitBreakerObservation",
    "CircuitBreakerPolicy",
    "CircuitBreakerState",
    "HttpCircuitBreakerServer",
    "HttpBulkheadPolicy",
    "HttpBulkheadServer",
    "HttpHandler",
    "HttpCachePolicy",
    "HttpCacheServer",
    "HttpFault",
    "HttpFaultInjectionServer",
    "HttpMultiplexerRuntime",
    "HttpMultiplexerServer",
    "HttpProxyRuntime",
    "HttpProxyServer",
    "HttpRateLimiterRuntime",
    "HttpRateLimiterServer",
    "HttpRetryServer",
    "HttpTrafficLoggerServer",
    "HttpTimeoutServer",
    "HttpTimeoutPolicy",
    "HttpRequest",
    "HttpResponse",
    "ConnectionTerminationFault",
    "DelayFault",
    "DisabledFaultInjection",
    "EnabledFaultInjection",
    "FaultInjectionLimits",
    "FaultInjectionObservation",
    "FaultInjectionState",
    "FaultKind",
    "InjectedConnectionTermination",
    "InjectedHttpStatus",
    "SeededProbabilityFault",
    "StatusFault",
    "TargetOutcome",
    "TruncationFault",
    "HttpWeightedLoadBalancerRuntime",
    "HttpWeightedLoadBalancerServer",
    "ManagedRouterEnvironment",
    "ManagedRouterSettings",
    "CapabilityImplementation",
    "ExecutableCapability",
    "PACKAGE_SERVER_CONTRACTS",
    "PackageServerContract",
    "ProductMaturity",
    "RequestObservation",
    "RequestObserverServer",
    "RetryMethodPolicy",
    "RetryObservation",
    "RetryPolicy",
    "RetryStatusPolicy",
    "TrafficEvidence",
    "TrafficEvidencePage",
    "TrafficEvidencePolicy",
    "TrafficMethod",
    "TrafficPathPolicy",
    "TrafficStatusClass",
    "TimeoutObservation",
    "TimeoutOutcome",
    "UnsupportedCapability",
    "create_block_control_app",
    "create_instance_read_app",
    "create_managed_http_router_app",
    "hello_command",
    "hello_server_block",
    "http_active_router_block",
    "http_active_router_command",
    "http_circuit_breaker_block",
    "http_circuit_breaker_command",
    "http_bulkhead_block",
    "http_bulkhead_command",
    "http_cache_block",
    "http_cache_command",
    "fault_injection_state_descriptor",
    "fault_injection_state_from_descriptor",
    "http_fault_injector_block",
    "http_fault_injector_command",
    "http_multiplexer_block",
    "http_multiplexer_command",
    "http_proxy_block",
    "http_proxy_command",
    "http_rate_limiter_block",
    "http_rate_limiter_command",
    "http_retry_block",
    "http_retry_command",
    "http_traffic_logger_block",
    "http_traffic_logger_command",
    "http_timeout_block",
    "http_timeout_command",
    "http_weighted_load_balancer_block",
    "http_weighted_load_balancer_command",
    "managed_http_router_block",
    "package_server_contract",
    "request_observer_block",
    "request_observer_command",
]
