"""Narrow persistence capabilities owned by the idempotency gateway."""

from __future__ import annotations

from typing import Protocol, Self

from control_plane_kit.domains.idempotency import IdempotencyRecord, IdempotencyRecordStatus


class IdempotencyStore(Protocol):
    def lock_key(self, gateway_id: str, tenant_fingerprint: str, key_fingerprint: str) -> None: ...
    def add(self, record: IdempotencyRecord) -> IdempotencyRecord: ...
    def get_for_key(self, gateway_id: str, tenant_fingerprint: str, key_fingerprint: str) -> IdempotencyRecord | None: ...
    def complete(self, request_id: str, *, expected: IdempotencyRecordStatus, replacement: IdempotencyRecordStatus, result_status: int, result_reference: str | None, completed_at: str) -> IdempotencyRecord | None: ...
    def mark_uncertain(self, request_id: str) -> IdempotencyRecord | None: ...
    def delete_expired_terminal(self, gateway_id: str, observed_at: str) -> int: ...
    def count_for_gateway(self, gateway_id: str) -> int: ...


class IdempotencyUnitOfWork(Protocol):
    @property
    def store(self) -> IdempotencyStore: ...
    def __enter__(self) -> Self: ...
    def commit(self) -> None: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...
