"""Operational webhook-delivery entrance."""

from control_plane_kit._optional import require_optional_dependencies

require_optional_dependencies(
    "control_plane_kit.webhook",
    ("fastapi", "httpx"),
    extra="http",
)

from control_plane_kit.webhook.postgres import (
    WEBHOOK_POSTGRES_SCHEMA,
    PostgresWebhookCommandRecord,
    PostgresWebhookCommandStore,
    PostgresWebhookIntentStore,
    PostgresWebhookJournalStore,
    PostgresWebhookProjectionRecord,
    PostgresWebhookProjectionStore,
    install_webhook_schema,
)
from control_plane_kit.webhook.protocols import (
    WebhookCommandRecord,
    WebhookCommandStore,
    WebhookIntentStore,
    WebhookJournalStore,
    WebhookProjectionRecord,
    WebhookProjectionStore,
    WebhookUnitOfWork,
)
from control_plane_kit.webhook.unit_of_work import PostgresWebhookUnitOfWork
from control_plane_kit.webhook.service import (
    ClaimWebhook,
    DispatchWebhook,
    EnqueueWebhook,
    RecoverWebhook,
    ReleaseWebhookClaim,
    WebhookAuthorizationError,
    WebhookCommand,
    WebhookCommandConflict,
    WebhookCommandKind,
    WebhookCommandResult,
    WebhookDeliveryService,
    WebhookOutboundDelivery,
    WebhookOutboundRequest,
    WebhookOutboundResult,
    WebhookReadResult,
    WebhookServiceError,
    WebhookStateConflict,
    webhook_delivery_descriptor,
)
from control_plane_kit.webhook.http import (
    HttpWebhookDelivery,
    SystemWebhookPublicAddressResolver,
    WebhookAddressPolicy,
    WebhookEndpointGrant,
    WebhookEndpointScope,
    WebhookHttpLimits,
    WebhookHttpSecurityError,
    WebhookPublicAddressResolver,
)
from control_plane_kit.webhook.app import (
    MAX_WEBHOOK_API_REQUEST_BYTES,
    MAX_WEBHOOK_API_RESPONSE_BYTES,
    create_webhook_delivery_app,
)

__all__ = [
    "MAX_WEBHOOK_API_REQUEST_BYTES",
    "MAX_WEBHOOK_API_RESPONSE_BYTES",
    "WEBHOOK_POSTGRES_SCHEMA",
    "PostgresWebhookCommandRecord",
    "PostgresWebhookCommandStore",
    "PostgresWebhookIntentStore",
    "PostgresWebhookJournalStore",
    "PostgresWebhookProjectionRecord",
    "PostgresWebhookProjectionStore",
    "PostgresWebhookUnitOfWork",
    "WebhookCommandRecord",
    "WebhookCommandStore",
    "WebhookIntentStore",
    "WebhookJournalStore",
    "WebhookProjectionRecord",
    "WebhookProjectionStore",
    "WebhookUnitOfWork",
    "install_webhook_schema",
    "ClaimWebhook",
    "DispatchWebhook",
    "EnqueueWebhook",
    "RecoverWebhook",
    "ReleaseWebhookClaim",
    "WebhookAuthorizationError",
    "WebhookCommand",
    "WebhookCommandConflict",
    "WebhookCommandKind",
    "WebhookCommandResult",
    "WebhookDeliveryService",
    "WebhookOutboundDelivery",
    "WebhookOutboundRequest",
    "WebhookOutboundResult",
    "WebhookReadResult",
    "HttpWebhookDelivery",
    "SystemWebhookPublicAddressResolver",
    "WebhookAddressPolicy",
    "WebhookEndpointGrant",
    "WebhookEndpointScope",
    "WebhookHttpLimits",
    "WebhookHttpSecurityError",
    "WebhookPublicAddressResolver",
    "create_webhook_delivery_app",
    "WebhookServiceError",
    "WebhookStateConflict",
    "webhook_delivery_descriptor",
]
